<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AnalysisLevel>latest-all</AnalysisLevel>
    <AssemblyName>ProjectTemplateTests</AssemblyName>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <NeutralLanguage>en</NeutralLanguage>
    <Nullable>enable</Nullable>
    <RootNamespace>ptr727.ProjectTemplate.Tests</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AwesomeAssertions" Version="9.3.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.analyzers" Version="1.27.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" PrivateAssets="All" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Library\Library.csproj" />
    <ProjectReference Include="..\Console\Console.csproj" />
  </ItemGroup>
</Project>
