<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <Authors>Pieter Viljoen</Authors>
    <Company>Pieter Viljoen</Company>
    <Copyright>Pieter Viljoen</Copyright>
    <Description>C# .NET template project</Description>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <FileVersion>1.0.0.0</FileVersion>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IncludeSymbols>true</IncludeSymbols>
    <InformationalVersion>1.0.0-pre</InformationalVersion>
    <IsAotCompatible>true</IsAotCompatible>
    <IsPackable>true</IsPackable>
    <PackageId>ptr727.ProjectTemplate.Library</PackageId>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/ptr727/ProjectTemplate</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>ProjectTemplate</PackageTags>
    <PackageVersion>1.0.0-pre</PackageVersion>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <RepositoryUrl>https://github.com/ptr727/ProjectTemplate</RepositoryUrl>
    <RootNamespace>ptr727.ProjectTemplate.NuGetLibrary</RootNamespace>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <Version>1.0.0.0</Version>
  </PropertyGroup>
  <PropertyGroup Condition="'$(IsPublish)' == 'true'">
    <VerifyReferenceAotCompatibility>true</VerifyReferenceAotCompatibility>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Console" />
    <InternalsVisibleTo Include="Tests" />
    <InternalsVisibleTo Include="Benchmarks" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="" />
  </ItemGroup>
</Project>
