name: Build and publish project release

on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build-project:
    name: Build project
    permissions:
      contents: write
    uses: ./.github/workflows/build-project-task.yml
    secrets: inherit
    with:
      # Push to GitHub and NuGet
      github: true
      nuget: true

  date-badge:
    name: Create date badge
    permissions:
      contents: write
    needs: [build-project]
    uses: ./.github/workflows/date-badge-task.yml
    secrets: inherit
