name: Build and publish project release

on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build-project:
    name: Build project
    uses: ./.github/workflows/build-project-task.yml
    secrets: inherit
    with:
      github: true
      nuget: true

  date-badge:
    if: ${{ endsWith(github.ref, 'refs/heads/main') }}
    needs: build-project
    name: Create date badge
    uses: ./.github/workflows/date-badge-task.yml
    secrets: inherit
