name: Test project build PRs

on:
  pull_request:
    branches: [ main, develop ]
    paths-ignore:
      # Ignore Docker-related files
      - 'Docker/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  test-build:
    name: Run build tests
    uses: ./.github/workflows/test-project-task.yml
    secrets: inherit
